server:
  port: 9001

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    example1: topic-1
    example2: topic-2
    messages-per-request: 10

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.acme: DEBUG