spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
       group-id: example-group
       auto-offset-reset: earliest

app:
  topic:
    example-string: topic-string
    example-json: topic-json
    example-bytearray: topic-bytearray

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.acme: DEBUG