version: '3'

services:

    producer:
        image: acme/demo-kafka-spring-boot-producer
        environment:
          BROKER: localhost:9092
        network_mode: host


    consumer:
        image: acme/demo-kafka-spring-boot-consumer
        environment:
          BROKER: localhost:9092
          MESSAGE_PROCESSING_TIME: 2000
        network_mode: host


