version: '3'

services:

    producer:
        image: acme/demo-kafka-spring-boot-producer
        environment:
          BROKER: kafka1:19091

    consumer:
        image: acme/demo-kafka-spring-boot-consumer
        environment:
          BROKER: kafka2:19092
          MESSAGE_PROCESSING_TIME: 2000
