spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: consumer-group-1
      auto-offset-reset: earliest

app:
  topic:
    example1: topic-1
    example2: topic-2

message:
  processing:
    time: 0

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.acme: DEBUG